package com.zuhlke.testing.recmocks;

/**
 * A mock is identified by the underlying object's class
 * and the id generated by the context that was active during the mock's creation.
 */
public class MockedObjectId {
    private final String objectClass;
    private final int id;

    public MockedObjectId(String objectClass, int id) {
        this.objectClass = objectClass;
        this.id = id;
    }

    @Override
    public String toString() {
        return objectClass + "." + id;
    }
}
